# Generated by Django 4.2.4 on 2023-08-29 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=3)),
                ('donation_option', models.CharField(choices=[('replacement', 'Replacement'), ('voluntary', 'Voluntary')], default='Voluntary', max_length=20)),
                ('donation_type', models.CharField(choices=[('regular', 'Regular'), ('platelets', 'Platelets'), ('plasma', 'Plasma'), ('double_red_cells', 'Double Red Cells')], default='Regular', max_length=20)),
                ('number_of_pints', models.PositiveIntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('age', models.PositiveIntegerField(default=18)),
                ('donor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('donor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Stale', 'Stale'), ('Listed', 'Listed'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Rejected', 'Rejected'), ('Verified', 'Verified')], default='Pending', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('verification_photo', models.ImageField(blank=True, null=True, upload_to='donor_photos')),
                ('potential_lives_saved', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Blood Donations',
            },
        ),
        migrations.CreateModel(
            name='DonationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Donation Targets',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile_name', models.CharField(max_length=50)),
                ('blood_type', models.CharField(max_length=5)),
                ('profile_avatar', models.ImageField(blank=True, upload_to='profile_avatars')),
                ('number_of_donations', models.PositiveIntegerField(default=0)),
                ('potential_lives_saved', models.PositiveIntegerField(default=0)),
                ('donation_history', models.ManyToManyField(blank=True, to='donation.donation')),
                ('donation_targets', models.ManyToManyField(blank=True, related_name='user_profiles', to='donation.donationtarget')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AddField(
            model_name='donationtarget',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.userprofile'),
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=3)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Stale', 'Stale'), ('Listed', 'Listed'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Rejected', 'Rejected'), ('Verified', 'Verified')], default='Pending', max_length=20)),
                ('donation_option', models.CharField(choices=[('replacement', 'Replacement'), ('voluntary', 'Voluntary')], default='Voluntary', max_length=20)),
                ('donation_type', models.CharField(choices=[('regular', 'Regular'), ('platelets', 'Platelets'), ('plasma', 'Plasma'), ('double_red_cells', 'Double Red Cells')], default='Regular', max_length=20)),
                ('number_of_pints', models.PositiveIntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('age', models.PositiveIntegerField(default=18)),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_story', models.TextField()),
                ('patient_avatar', models.ImageField(blank=True, upload_to='patient_avatars')),
                ('hospital', models.CharField(blank=True, max_length=100, null=True)),
                ('donors_needed', models.PositiveIntegerField(default=1)),
                ('pending_donations', models.ManyToManyField(blank=True, related_name='pending_requests', to='donation.donation')),
                ('verified_donations', models.ManyToManyField(blank=True, related_name='verified_requests', to='donation.donation')),
            ],
            options={
                'verbose_name_plural': 'Donation Requests',
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donation.donationrequest'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
