# Generated by Django 4.2.4 on 2023-09-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_remove_donationrequest_pending_donations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='is_rejected',
        ),
        migrations.AddField(
            model_name='donation',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
