# Generated by Django 4.2.5 on 2023-09-08 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_remove_donationrequest_pending_donations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='is_rejected',
        ),
    ]
