# Generated by Django 4.2.4 on 2023-09-13 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donation', '0003_remove_donation_is_canceled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DonationPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_donations', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_donations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_text', models.TextField()),
                ('reference_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonationPlanDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('donation_drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donationdrive')),
                ('donation_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donationplan')),
            ],
        ),
        migrations.AddField(
            model_name='donationplan',
            name='donation_drives',
            field=models.ManyToManyField(through='donation.DonationPlanDrive', to='donation.donationdrive'),
        ),
        migrations.AddField(
            model_name='donationplan',
            name='donations',
            field=models.ManyToManyField(to='donation.donation'),
        ),
        migrations.AddField(
            model_name='donationplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.userprofile'),
        ),
        migrations.CreateModel(
            name='DonationDriveOrganizer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organizer_name', models.CharField(max_length=100)),
                ('profile_avatar', models.ImageField(blank=True, upload_to='organizer_avatars')),
                ('biography', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('availability', models.BooleanField(default=True)),
                ('organizer_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('social_media_profiles', models.ManyToManyField(blank=True, related_name='organizers', to='donation.socialmediaprofile')),
                ('testimonials', models.ManyToManyField(blank=True, related_name='organizers', to='donation.testimonial')),
                ('upcoming_donation_drives', models.ManyToManyField(blank=True, to='donation.donationdrive')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donationdriveorganizer'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donation.donationdrive'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.donationplan'),
        ),
    ]
