# Generated by Django 4.2.4 on 2023-09-14 09:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_donationdrive_donationplan_socialmediaprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='donationplan',
            old_name='donations',
            new_name='pending_donations',
        ),
        migrations.RenameField(
            model_name='donationplan',
            old_name='donation_drives',
            new_name='selected_drives',
        ),
        migrations.RenameField(
            model_name='donationplan',
            old_name='user',
            new_name='user_profile',
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='HospitalAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Scheduled', max_length=20)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.hospital')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='donationplan',
            name='preferred_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donation.hospital'),
        ),
    ]
